# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AtmGui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import QCoreApplication
import pyttsx3
from db import Update,Read,establish_connection

#setting of engine to taking voice 
eng=pyttsx3.init('sapi5')          
voices=eng.getProperty('voices')
eng.setProperty('voices',voices[0].id)
eng.setProperty('rate',170)              #speech rate in words per minute

class Ui_MainWindow(object):
    
    def closeMain(self,win):
        win.hide()

    
    def Speak(self,text):
        self.audio=text
        eng.say(self.audio)
        print("")
        eng.runAndWait() 

    def setupUi(self, MainWindow,mob,PIN):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1214, 758)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        
        self.mob=mob
        self.PIN=PIN
        self.flag=3

        self.msg = QtWidgets.QMessageBox()
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(-6, -5, 1221, 761))
        self.label.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.124378, y1:0.119, x2:1, y2:1, stop:0.18408 rgba(0, 73, 113, 255), stop:0.850746 rgba(27, 0, 68, 255));\n"
"")
        self.label.setText("")
        self.label.setObjectName("label")
        self.greenpin = QtWidgets.QPushButton(self.centralwidget)
        self.greenpin.setGeometry(QtCore.QRect(0, 80, 271, 71))
        self.greenpin.setStyleSheet(
"background-color: rgb(0, 0, 59);\n"
"font: 18pt \"Sitka\";\n"
"color:aqua;\n"
"border-radius:10px;\n"
"border-bottom:2px solid aqua;\n"
)
        self.greenpin.setObjectName("greenpin")
        self.withdrawal = QtWidgets.QPushButton(self.centralwidget)
        self.withdrawal.setGeometry(QtCore.QRect(0, 240, 271, 71))
        self.withdrawal.setStyleSheet("background-color: rgb(0, 0, 59);\n"
"font: 18pt \"Sitka\";\n"
"color:aqua;\n"
"border-radius:10px;\n"
"border-bottom:2px solid aqua;")
        self.withdrawal.setObjectName("withdrawal")
        self.changepin = QtWidgets.QPushButton(self.centralwidget)
        self.changepin.setGeometry(QtCore.QRect(940, 80, 271, 71))
        self.changepin.setStyleSheet("background-color: rgb(0, 0, 59);\n"
"font: 18pt \"Sitka\";\n"
"color:aqua;\n"
"border-radius:10px;\n"
"border-bottom:2px solid aqua;")
        self.changepin.setObjectName("changepin")
        self.deposit = QtWidgets.QPushButton(self.centralwidget)
        self.deposit.setGeometry(QtCore.QRect(940, 220, 271, 71))
        self.deposit.setStyleSheet("background-color: rgb(0, 0, 59);\n"
"font: 18pt \"Sitka\";\n"
"color:aqua;\n"
"border-radius:10px;\n"
"border-bottom:2px solid aqua;")
        self.deposit.setObjectName("deposit")
        self.textbox = QtWidgets.QTextBrowser(self.centralwidget)
        self.textbox.setGeometry(QtCore.QRect(300, 20, 641, 41))
        self.textbox.setStyleSheet("color: rgb(114, 255, 239);\n"
"background-color:transparent;\n"
"border:none;\n"
"font: 16pt \"OCR A Extended\";")
        self.textbox.setObjectName("textbox")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(430, 150, 371, 321))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(3)
        self.gridLayout.setObjectName("gridLayout")
        self.two = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.two.setMinimumSize(QtCore.QSize(30, 62))
        self.two.setMaximumSize(QtCore.QSize(148, 28))
        self.two.setStyleSheet("background-color: rgb(0, 170, 255);\n"
"font: 28pt \"MV Boli\";\n"
"color: rgb(255, 255, 255);\n"
"border-radius:30px;")
        self.two.setObjectName("two")
        self.gridLayout.addWidget(self.two, 2, 1, 1, 1)
        self.four = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.four.setMinimumSize(QtCore.QSize(30, 62))
        self.four.setMaximumSize(QtCore.QSize(148, 28))
        self.four.setStyleSheet("background-color: rgb(0, 170, 255);\n"
"font: 28pt \"MV Boli\";\n"
"color: rgb(255, 255, 255);\n"
"border-radius:30px;")
        self.four.setObjectName("four")
        self.gridLayout.addWidget(self.four, 1, 0, 1, 1)
        self.three = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.three.setMinimumSize(QtCore.QSize(30, 62))
        self.three.setMaximumSize(QtCore.QSize(148, 28))
        self.three.setStyleSheet("background-color: rgb(0, 170, 255);\n"
"font: 28pt \"MV Boli\";\n"
"color: rgb(255, 255, 255);\n"
"border-radius:30px;")
        self.three.setObjectName("three")
        self.gridLayout.addWidget(self.three, 2, 2, 1, 1)
        self.five = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.five.setMinimumSize(QtCore.QSize(30, 62))
        self.five.setMaximumSize(QtCore.QSize(148, 28))
        self.five.setStyleSheet("background-color: rgb(0, 170, 255);\n"
"font: 28pt \"MV Boli\";\n"
"color: rgb(255, 255, 255);\n"
"border-radius:30px;")
        self.five.setObjectName("five")
        self.gridLayout.addWidget(self.five, 1, 1, 1, 1)
        self.seven = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.seven.setMinimumSize(QtCore.QSize(30, 62))
        self.seven.setMaximumSize(QtCore.QSize(148, 28))
        self.seven.setStyleSheet("background-color: rgb(0, 170, 255);\n"
"font: 28pt \"MV Boli\";\n"
"color: rgb(255, 255, 255);\n"
"border-radius:30px;\n"
"\n"
"")
        self.seven.setObjectName("seven")
        self.gridLayout.addWidget(self.seven, 0, 0, 1, 1)
        self.one = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.one.setMinimumSize(QtCore.QSize(30, 62))
        self.one.setMaximumSize(QtCore.QSize(148, 28))
        self.one.setStyleSheet("background-color: rgb(0, 170, 255);\n"
"font: 28pt \"MV Boli\";\n"
"color: rgb(255, 255, 255);\n"
"border-radius:30px;")
        self.one.setObjectName("one")
        self.gridLayout.addWidget(self.one, 2, 0, 1, 1)
        self.six = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.six.setMinimumSize(QtCore.QSize(30, 62))
        self.six.setMaximumSize(QtCore.QSize(148, 28))
        self.six.setStyleSheet("background-color: rgb(0, 170, 255);\n"
"font: 28pt \"MV Boli\";\n"
"color: rgb(255, 255, 255);\n"
"border-radius:30px;")
        self.six.setObjectName("six")
        self.gridLayout.addWidget(self.six, 1, 2, 1, 1)
        self.eight = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.eight.setMinimumSize(QtCore.QSize(30, 62))
        self.eight.setMaximumSize(QtCore.QSize(148, 28))
        self.eight.setStyleSheet("background-color: rgb(0, 170, 255);\n"
"font: 28pt \"MV Boli\";\n"
"color: rgb(255, 255, 255);\n"
"border-radius:30px;")
        self.eight.setObjectName("eight")
        self.gridLayout.addWidget(self.eight, 0, 1, 1, 1)
        self.nine = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.nine.setMinimumSize(QtCore.QSize(30, 62))
        self.nine.setMaximumSize(QtCore.QSize(148, 28))
        self.nine.setStyleSheet("background-color: rgb(0, 170, 255);\n"
"font: 28pt \"MV Boli\";\n"
"color: rgb(255, 255, 255);\n"
"border-radius:30px;")
        self.nine.setObjectName("nine")
        self.gridLayout.addWidget(self.nine, 0, 2, 1, 1)
        self.zero = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.zero.setMinimumSize(QtCore.QSize(30, 62))
        self.zero.setMaximumSize(QtCore.QSize(148, 28))
        self.zero.setStyleSheet("background-color: rgb(0, 170, 255);\n"
"font: 28pt \"MV Boli\";\n"
"color: rgb(255, 255, 255);\n"
"border-radius:30px;")
        self.zero.setObjectName("zero")
        self.gridLayout.addWidget(self.zero, 3, 1, 1, 1)
        self.clr = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.clr.setMinimumSize(QtCore.QSize(30, 62))
        self.clr.setMaximumSize(QtCore.QSize(148, 28))
        self.clr.setStyleSheet("background-color: rgb(41, 73, 255);\n"
"font: 28pt \"MV Boli\";\n"
"color: rgb(255, 255, 255);\n"
"border-radius:30px;")
        self.clr.setObjectName("clr")
        self.gridLayout.addWidget(self.clr, 3, 0, 1, 1)
        self.Del = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.Del.setMinimumSize(QtCore.QSize(30, 62))
        self.Del.setMaximumSize(QtCore.QSize(148, 28))
        self.Del.setStyleSheet("background-color: rgb(3, 9, 26);\n"
"font: 28pt \"MV Boli\";\n"
"color: rgb(255, 255, 255);\n"
"border-radius:30px;")
        self.Del.setObjectName("del")
        self.gridLayout.addWidget(self.Del, 3, 2, 1, 1)
        self.proceed = QtWidgets.QPushButton(self.centralwidget)
        self.proceed.setGeometry(QtCore.QRect(490, 490, 251, 61))
        self.proceed.setStyleSheet("\n"
"font: 28pt ;\n"
"border-radius:10px;\n"
"background-color: rgb(65, 255, 112);")
        self.proceed.setObjectName("proceed")
        self.video = QtWidgets.QLabel(self.centralwidget)
        self.video.setGeometry(QtCore.QRect(960, 530, 241, 211))
        self.video.setStyleSheet("border:2px solid grey;")
        self.video.setText("")
        self.video.setObjectName("video")

        self.card = QtWidgets.QPushButton(self.centralwidget,clicked=lambda:self.closeMain(MainWindow))
        self.card.setText("CLOSE")
        self.card.setGeometry(QtCore.QRect(30, 640, 351, 81))

        self.card.setStyleSheet("\n"
"font: 28pt ;\n"
"border-radius:10px;\n"
"background-color:red;\n"
"color:white;\n"
"border:1px solid grey;")
        self.card.setObjectName("card")
        self.inputbox = QtWidgets.QTextBrowser(self.centralwidget)
        self.inputbox.setGeometry(QtCore.QRect(340, 70, 520, 80))
        self.inputbox.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.124378, y1:0.119, x2:1, y2:1, stop:0.18408 rgba(0, 0, 0, 147), stop:0.850746 rgba(3, 0, 7, 255));\n"
"font: 28pt \"MV Boli\";\n"
"color: rgb(85, 255, 38);\n"
"border:none;\n"
"border-radius:10px;\n"
"border-bottom:2px solid grey;\n"
"border-left:2px solid grey;")
        self.inputbox.setObjectName("inputbox")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        #intance to connect function to coresponding buttons=================================
        
        self.zero.clicked.connect(self.Zero)
        self.one.clicked.connect(self.One)
        self.two.clicked.connect(self.Two)
        self.three.clicked.connect(self.Three)
        self.four.clicked.connect(self.Four)
        self.five.clicked.connect(self.Five)
        self.six.clicked.connect(self.Six)
        self.seven.clicked.connect(self.Seven)
        self.eight.clicked.connect(self.Eight)
        self.nine.clicked.connect(self.Nine)
        self.clr.clicked.connect(self.CLR)
        self.Del.clicked.connect(self.DEL)

        self.changepin.clicked.connect(self.Changepin)
        self.withdrawal.clicked.connect(self.Withdrawal) 

        #self.c.clicked.connect(self.Card)
        self.proceed.clicked.connect(self.Proceed)

        #self.card.clicked.connect(QCoreApplication.instance().quit)
        #self.card.clicked.connect(self.exit)

        #Methods for each button===================================================
    
    def quit(self):
        self.exit()

    def Zero(self):
        self.inputbox.setText(self.inputbox.toPlainText()+"0")
    def One(self):
        self.inputbox.setText(self.inputbox.toPlainText()+"1")
    def Two(self):
        self.inputbox.setText(self.inputbox.toPlainText()+"2")
    def Three(self):
        self.inputbox.setText(self.inputbox.toPlainText()+"3")
    def Four(self):
        self.inputbox.setText(self.inputbox.toPlainText()+"4")
    def Five(self):
        self.inputbox.setText(self.inputbox.toPlainText()+"5")
    def Six(self):
        self.inputbox.setText(self.inputbox.toPlainText()+"6")
    def Seven(self):
        self.inputbox.setText(self.inputbox.toPlainText()+"7")
    def Eight(self):
        self.inputbox.setText(self.inputbox.toPlainText()+"8")
    def Nine(self):
        self.inputbox.setText(self.inputbox.toPlainText()+"9")
    
    def CLR(self):
        self.inputbox.setText("")
    def DEL(self):
        self.inputbox.setText(self.inputbox.toPlainText()[:-1])


    def Changepin(self):
        self.textbox.setText("\t\tEnter The New Pin")
        self.Speak("Enter The New PIN")
        self.flag=4

    def Withdrawal(self):
        self.flag=0
        self.textbox.setText("\t\tEnter The Amount")
        self.Speak("Enter The Amount")

    def Proceed(self):
        if self.flag==0:                                #for withdrawal
                if self.inputbox.toPlainText()!="":
                        self.amount=int(self.inputbox.toPlainText())
                        print(self.mob)
                        establish_connection()
                        self.BALANCE = Read("select balance from customer where ph_no={}".format(self.mob))
                        print(self.BALANCE)
                        if self.BALANCE==None:
                                print("TRY AGAIN!!")

                        elif self.amount>int(self.BALANCE):
                                self.Speak("No enough balance in account")
                                self.messagebox("You don't have enough balance in account\nYOUR BALANCE:%s"%(self.BALANCE),2)
                                self.flag=0
                                
                        else:
                                self.textbox.setText("\t\tEnter Your PIN")
                                self.inputbox.setText("")
                                self.flag=1
                                self.Speak("Enter Your PIN")
                                self.flag=1
        if self.flag==1:                                #for pin
                if self.inputbox.toPlainText()!="":
                        self.pin=int(self.inputbox.toPlainText())
                        self.flag=2
                
        if self.flag==2:                                #for cross verify the pin
                if str(self.pin)==str(self.PIN):
                        establish_connection()
                        Update("update customer set balance=balance-{} where ph_no={}".format (self.amount,self.mob ))
                        self.Speak("Transaction Successful !")
                        self.messagebox("Withdrawal Amount:%s\nTake the Money from Money Box"%(self.amount),1)
                        self.inputbox.setText("")
                        self.flag=3
                        self.textbox.setText("")

                else:
                        self.Speak("Incorrect PIN")
                        self.messagebox("Incorrect PIN",2)
                        self.inputbox.setText("")
                        self.flag=1

        if self.flag==4:
                if self.inputbox.toPlainText()!="":
                        self.pin=int(self.inputbox.toPlainText())
                        self.pin1=self.pin
                        self.flag=3
                        self.messagebox("PIN has been changed Successfully !",1)
                        self.inputbox.setText("")
                        

        
    def messagebox(self,message,type):              #type 1= information message / type 2 = warning message
        self.message=message
        self.type=type
                
        if self.type==1:
                self.msg.setIcon(self.msg.Information)

                # setting message for Message Box
                self.msg.setText(self.message)

                # setting Message box window title
                self.msg.setWindowTitle("Transaction Successful !!!")

                # declaring buttons on Message Box
                self.msg.setStandardButtons(self.msg.Ok | self.msg.Cancel)

        if self.type==2:
                self.msg.setIcon(self.msg.Warning)

                # setting message for Message Box
                self.msg.setText(self.message)

                # setting Message box window title
                self.msg.setWindowTitle("Warning !!!")

                # declaring buttons on Message Box
                self.msg.setStandardButtons(self.msg.Ok | self.msg.Cancel)


        # start the app
        retval = self.msg.exec_()


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.greenpin.setText(_translate("MainWindow", "Green Pin"))
        self.withdrawal.setText(_translate("MainWindow", "Cash Withdrawl"))
        self.changepin.setText(_translate("MainWindow", "Change Pin"))
        self.deposit.setText(_translate("MainWindow", "Cash Deposit"))
        self.textbox.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'OCR A Extended\'; font-size:16pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.two.setText(_translate("MainWindow", "2"))
        self.four.setText(_translate("MainWindow", "4"))
        self.three.setText(_translate("MainWindow", "3"))
        self.five.setText(_translate("MainWindow", "5"))
        self.seven.setText(_translate("MainWindow", "7"))
        self.one.setText(_translate("MainWindow", "1"))
        self.six.setText(_translate("MainWindow", "6"))
        self.eight.setText(_translate("MainWindow", "8"))
        self.nine.setText(_translate("MainWindow", "9"))
        self.zero.setText(_translate("MainWindow", "0"))
        self.clr.setText(_translate("MainWindow", "CLR"))
        self.Del.setText(_translate("MainWindow", "DEL"))
        self.proceed.setText(_translate("MainWindow", "Proceed"))
        self.card.setText(_translate("MainWindow", "CLOSE"))
        self.inputbox.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MV Boli\'; font-size:28pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
